### ISSUE TITLE
Addons plugin crash [BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#27] opened 2022-12-12 19:18 UTC
**Ashita Version** _(Type /ashita in-game to get this.)_
v4.0.0.6

**FFXI Version** _(Type /version in-game to get this.)_
30221206_0

**Windows Version** _(ie. Start > About Your PC)_
10 Pro 22H2
19045.2251

**Describe The Bug**
The addons plugin crashes on zone ins sometimes, this time to HP#1 in western adoulin

**Steps To Reproduce**
Unfortunately hard to reproduce but has happened several times always after zoning to a HP crystal, this time I saved the log so I could post here, hopefully the log helps I know it is not much information. I do have the entire log saved but this is a quick screenshot of the crash/error

**Screenshots**

![image](https://user-images.githubusercontent.com/66495755/207133244-c6e89b79-3ed7-4f94-a8a3-7b268a74536d.png)

**Comment by atom0s** [comment] 2022-12-24 03:38
This would land up being due to a specific addon doing something bad. Hard to say for sure what it is just based on that. It'd require a bit more testing on your end to narrow down which addon is causing it.

You'd need to unload most of your addons and only load 1 (or a few) at a time and keep trying to recrash until you can narrow down which one may be the cause.

**Comment by GetAwayCoxn** [comment] 2022-12-28 14:58
Understood, after all the holidays I should have some time to try and zero in on this. Anything I find I will update here of course, this does seem to happen often enough to be able to narrow it down :crossed_fingers:

**Comment by atom0s** [comment] 2023-05-14 02:19
I am going to close this and mark it as invalid as there has been no further activity. I believe a lot of your crash issues came from your work with ImGui and potentially incorrect/invalid push/pops of styles and other similar settings based on further chats on Discord. If you continue to have other crashes, feel free to make another ticket. :)

**Closed by atom0s** 2023-05-14 02:19 UTC
Labels: c: addon, p: medium, t: bug
